const START_ROUTE = '';
const REGISTER_ROUTE = 'register';
const LOGIN_ROUTE = 'login';
const HOME_ROUTE = 'home';

const PETS_LIST_VIEW_ROUTE = 'pets_list';
const ADD_PET_VIEW_ROUTE = 'add_pet';
const CLINICAL_HISTORIES_VIEW_ROUTE = 'clinical_histories';
const CALENDAR_VIEW_ROUTE = 'calendar';
const PROFILE_VIEW_ROUTE = 'profile';
const NOTIFICATIONS_ROUTE = 'notifications';
const SETTINGS_VIEW_ROUTE = 'settings';

const SIDE_BAR_VIEWS_ROUTES = [
  PETS_LIST_VIEW_ROUTE,
  CLINICAL_HISTORIES_VIEW_ROUTE,
  CALENDAR_VIEW_ROUTE,
  PROFILE_VIEW_ROUTE,
  NOTIFICATIONS_ROUTE,
  SETTINGS_VIEW_ROUTE,
];

const ULTRALARGE_BREAKPOINT = 1700;
const LARGE_BREAKPOINT = 1200;
const MEDIUM_BREAKPOINT = 700;

const SMALL_SCREEN_SIZE = 0;
const MEDIUM_SCREEN_SIZE = 1;
const LARGE_SCREEN_SIZE = 2;
const ULTRALARGE_SCREEN_SIZE = 3;
