const START_ROUTE = '/';
const REGISTER_ROUTE = '/register';
const LOGIN_ROUTE = '/login';
const HOME_ROUTE = '/home';

const PETS_VIEW_INDEX = 0;
const CLINICAL_HISTORIES_VIEW_INDEX = 1;
const CALENDAR_VIEW_INDEX = 2;
const PROFILE_VIEW_INDEX = 3;
const NOTIFICATIONS_INDEX = 4;
const SETTINGS_VIEW_INDEX = 5;

const ULTRALARGE_BREAKPOINT = 1700;
const LARGE_BREAKPOINT = 1200;
const MEDIUM_BREAKPOINT = 700;

const SMALL_SCREEN_SIZE = 0;
const MEDIUM_SCREEN_SIZE = 1;
const LARGE_SCREEN_SIZE = 2;
const ULTRALARGE_SCREEN_SIZE = 3;
